import { Montserrat } from "next/font/google";
import "./globals.css";
import Header, { HeaderUnderHeader } from "./components/Header";

const montserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
  weight: ['100', '400', '600', '700', '900'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <Header />
        <HeaderUnderHeader />
        {children}
      </body>
    </html>
  );
}
