import type { Metadata } from "next";
import "./globals.css";
import { Nunito_Sans } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import MediaLibraryProvider from "@/components/MediaLibraryProvider";


const nunitosans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <MediaLibraryProvider>
          <body
            className={`${nunitosans.className}`}
            >
            {children}
          </body>
        </MediaLibraryProvider>
      </SessionProvider>
    </html>
  );
}