import Image from 'next/image';
import React from 'react'

export const metadata = {
  title: "Auth | Dropify",
  description: "Generated by create next app",
};

export default function layout({children}) {
  return (
    <main className='flex'>
        <div className='relative w-full h-screen overflow-hidden'>
          <Image src='https://d2vw8tvocudf9g.cloudfront.net/assets/images/auth-background-1.svg' alt='' fill className='object-cover'/>
        </div>
        {children}
    </main>
  )
}
